//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-E63K26O;Initial Catalog=MegaServer;Integrated Security=True;C" +
            "onnect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string MegaServerConnectionString
        {
            get
            {
                return ((string)(this["MegaServerConnectionString"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        //[global::System.Configuration.DefaultSettingValueAttribute("Data Source=62.3.41.136,1433;Initial Catalog=DBA;User ID=qtest;Password=1qaz@WSX1401;Application Name=DBAApplication;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-E63K26O;Initial Catalog=DBA;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string DBAConnectionString
        {
            get
            {
                return ((string)(this["DBAConnectionString"]));
            }
        }


    }
}
